version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

    steps:
      - checkout
      # Install Vercel CLI
      - run:
          name: Install Vercel CLI
          command: npm install -g vercel

      # Deploy to Vercel
      - run:
          name: Deploy to Vercel
          command: |
            VERCEL_TOKEN=$VERCEL_TOKEN vercel --prod

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - build
